jenkins:
  image: jenkins-image
  links:
    - hub
  ports:
    - "8080:8080"
hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  links:
    - hub
chrome:
  image: selenium/node-chrome
  links:
    - hub
db:
  image: mysql:5.7
  volumes:
    - db_data:/var/lib/mysql
    - ../data/:/docker-entrypoint-initdb.d/
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: exxeta-consulting-and-technologies
    MYSQL_DATABASE: admin
    MYSQL_USER: admin
    MYSQL_PASSWORD: exxeta-consulting-and-technologies
  ports:
    - "3307:3306"
